# Generated by Django 6.0.6 on 2026-06-27 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carrito", "0001_initial"),
        ("productos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carrito",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carritos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carritoitem",
            name="carrito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="carrito.carrito",
            ),
        ),
        migrations.AddField(
            model_name="carritoitem",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="productos.producto"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="carritoitem",
            unique_together={("carrito", "producto")},
        ),
    ]
