# Generated by Django 6.0.6 on 2026-06-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
